// tslint:disable
/**
 * TailorShift API 1.0
 * This is the TailorShift API providing endpoints for the Edge PoS devices running in the TailorShift shops.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
